const fs = require('fs');
function fail(message){ console.error('ERRO:',message); process.exitCode=1; }
function assert(condition,message){ if(!condition) fail(message); }
const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const config=fs.readFileSync('js/config.js','utf8');
const css=fs.readFileSync('css/cnpj.css','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
assert(index.includes('1.0.19'),'index.html não está na versão 1.0.19');
assert(config.includes("version: '1.0.19'"),'config.js não está na versão 1.0.19');
assert(config.includes('946105310952-gp143h81mm3704lrq3877hsie49njgak.apps.googleusercontent.com'),'Client ID ausente');
assert(app.includes('Drive.discoverOfficialV118'),'descoberta automática da base real ausente');
assert(app.includes('Drive.listLikelyDataFilesV118'),'busca global de current.json ausente');
assert(app.includes('Drive.inspectRootV118'),'inspeção de pastas Sistema/Dados duplicadas ausente');
assert(app.includes('V118_PREFERRED_ROOT_ID'),'ID configurado não está sendo tratado como preferência');
assert(app.includes('Drive._pullOnceV118'),'carregamento seguro v1.0.19 ausente');
assert(app.includes('Drive.writeCanonicalV118'),'gravação canônica v1.0.19 ausente');
assert(app.includes("text.textContent='CARREGANDO . . .'"),'texto simples de carregamento ausente');
assert(!app.includes('Abrindo a pasta oficial da conta do seu pai'),'texto antigo de carregamento ainda existe');
assert(app.includes("V104_LOCAL_STATE_KEY='borion_cnpj_state_v2'"),'salvamento local v2 ausente');
assert(app.includes("const V115_CURRENT_FILE='current.json'"),'arquivo oficial current.json ausente');
assert(app.includes('Drive.runLocked'),'fila serial de sincronização ausente');
assert(app.includes('Drive.verifyCurrentV116'),'confirmação pós-gravação por releitura ausente');
assert(app.includes('v115AccountStateKey'),'estado local separado por conta ausente');
assert(app.includes('v116StateSignature'),'assinatura de confirmação ausente');
assert(index.includes("updateViaCache:'none'"),'atualização forçada do service worker ausente');
assert(app.includes('Drive.createSnapshot'),'snapshots do Drive ausentes');
assert(app.includes("'AUTO'"),'backup automático por sincronização ausente');
assert(app.includes("'DIARIO'"),'backup diário ausente');
assert(app.includes("'MENSAL'"),'backup mensal ausente');
assert(app.includes('chequeAccountSelectField'),'seleção de conta ausente');
assert(app.includes("label:'--'"),'opção -- ausente');
assert(app.includes('exportChequesImport'),'exportação de cheques ausente');
assert(app.includes('importChequesFile'),'importação de cheques ausente');
assert(app.includes('data-money'),'máscara monetária ausente');
assert(app.includes('formatDoc'),'máscara CPF/CNPJ ausente');
assert(css.includes('.settings-card'),'estética Borion de configurações ausente');
assert(index.includes('manifest.webmanifest'),'manifesto PWA ausente');
assert(index.includes('service-worker.js'),'registro do service worker ausente');
assert(index.includes('data-page="importar"'),'menu Importar arquivos ausente');
assert(app.includes('buildImportPlan'),'análise de importação ausente');
assert(app.includes('duplicates.cheques'),'detecção de cheques duplicados ausente');
assert(app.includes('duplicates.boletos'),'detecção de boletos duplicados ausente');
assert(app.includes('renderChequesDesktopV105'),'visualização mobile de cheques ausente');
assert(css.includes('.mobile-record-card'),'cartões mobile ausentes');
assert(fs.existsSync('manifest.webmanifest'),'arquivo manifest ausente');
assert(fs.existsSync('service-worker.js'),'service worker ausente');
assert(index.includes('borion-cnpj-v111-emblem.png'),'emblema oficial não referenciado');
assert(index.includes('borion-cnpj-v111-apple-touch-icon.png'),'ícone mobile oficial não referenciado');
assert(fs.existsSync('borion-cnpj-v111-icon-192.png'),'ícone 192 oficial ausente');
assert(fs.existsSync('borion-cnpj-v111-icon-512.png'),'ícone 512 oficial ausente');
assert(sw.includes("borion-cnpj-v1.0.19"),'cache PWA não está em 1.0.19');
if(!process.exitCode) console.log('BORION CNPJ 1.0.19 validado com sucesso.');
